### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by buzzworkers** [aurelg/feedspora#74]
```
$ python3 -m feedspora
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/feedspora/__main__.py", line 18, in <module>
    from feedspora.tweepy_client import TweepyClient  # @UnusedImport
  File "/usr/local/lib/python3.7/dist-packages/feedspora/tweepy_client.py", line 6, in <module>
    import tweepy
  File "/home/user2/.local/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/home/user2/.local/lib/python3.7/site-packages/tweepy/streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax
```

**Comment by aurelg** [comment]
Hi @buzzworkers. Seems like the issue is not in feedspora but in tweepy, and [has been fixed](https://github.com/tweepy/tweepy/pull/1042). You might want to run feedspora with python 3.6.x or (most likely) to update tweepy.

**Comment by manumacron** [comment]
I got the same issue with a fresh install.

```
 File "/my_home/.local/lib/python3.8/site-packages/tweepy/streaming.py", line 358
     def _start(self, async):
```
I checked online and found that it's related with a new version of python3 :
https://github.com/tweepy/tweepy/issues/1017

I follow the bypass, and replace every `async` with `async_` and it's work (pretty well, thx u !)

According to the github repository, the current version of tweety (3.10) seems to be fix this issue
