### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by nedson** [aurelg/feedspora#81]
Could anyone assist? After installing using the instructions posted, I run python3 -m feedspora,  I get this error:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/feedspora/__main__.py", line 100, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/feedspora/__main__.py", line 84, in main
    config = read_config_file(root_name + '.yml')
  File "/usr/local/lib/python3.9/dist-packages/feedspora/__main__.py", line 33, in read_config_file
    return load(config_file)
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by nedson** [comment]
Okay! 

The solution is:

!pip install pyyaml==5.4.1

Now I am seeing this error:

AttributeError: 'NoneType' object has no attribute 'text'
